global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'reservation-service'
    metrics_path: /api/v1/reservation-service/metrics
    scheme: https
    static_configs:
      - targets: ['metop.ir']

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
